### ISSUE TITLE
Some repos don't count 

### ISSUE THREAD

**Issue by Shwetago** [OtacilioN/awesome-hacktoberfest-2020#95]
There are some repos which don't count towards hacktoberfest 2019. Try to remove those as it will save time.

**Comment by OtacilioN** [comment]
Hey @Shwetago can you open a Pull Request removing those repositories? Thanks.

**Comment by OtacilioN** [comment]
I'm also adding a label here for those that want to contribute with that awesome list checking if it has repositories that do not count at Hacktoberfest 2019.

**Comment by Shwetago** [comment]
Yes I will @OtacilioN

**Comment by arshadkazmi42** [comment]
I think this will help you in filtering out those repositories
https://hacktober-xrepos.netlify.com/

**Comment by Shwetago** [comment]
Thanks for sharing @arshadkazmi42.
This will definitely help beginners and save their time.
I think you should include above link in the readme @OtacilioN

**Comment by erin-sparkbox** [comment]
Can I help with this issue?

**Comment by Shwetago** [comment]
@erin-sparkbox I have solved this issue and waiting for my pull request for merger.

**Comment by erin-sparkbox** [comment]
okay, thanks @Shwetago!

**Comment by beugenio** [comment]
Can I remove https://github.com/rishabh-bansal/GitStart for the list? @OtacilioN ?
